version: '3.4'

services:
  corkedfever.education.service:
    image: ${DOCKER_REGISTRY-}corkedfevereducationservice
    build:
      context: Corkedfever.Education.Service
      dockerfile: Dockerfile
